#!/usr/bin/env bash

echo "== deploy ec2 instance to interact with redis "

STACK_NAME="ec2-4-redis"

aws cloudformation deploy \
--template-file template.yaml \
--stack-name $STACK_NAME \
--capabilities CAPABILITY_IAM \
--no-execute-changeset \
--region us-east-1
