#!/usr/bin/env bash

echo "==list newest buckets"

# aws s3 ls
#aws s3api list-buckets | jq -r '.Buckets | sort by(.CreationDate) | reverse | .[] |.Name'
aws s3api list-buckets | jq -r '.Buckets | sort_by(.CreationDate) | reverse |.[0] | .Name'
