#!/usr/bin/env bash

yq -o=json '.' policy.yaml > policy.json

aws iam create-policy-version \
    --policy-arn arn:aws:iam::378950443697:policy/my-fun-policy \
    --policy-document file://policy.json \
    --set-as-default